package jabratech:component-greeks;

interface greeks {
    use jabratech:common/types.{option-kind};

    record request-greeks {
        option_kind: option-kind,
        spot_rate: f64,
        strike: f64,
        time_to_maturity: f64,
        domestic_interest_rate: f64,
        foreign_interest_rate: f64,
        volatility: f64,
    }

    record response-greeks {
        delta: f64,
        gamma: f64,
        theta: f64,
    }

    calculate-greeks: func(request: request-greeks) -> result<response-greeks, string>;

}

world component-greeks {

    export greeks;

}